# Test against this version of node.js

environment:
  matrix:
    # node.js
    - nodejs_version: "12"

# Install scripts. (runs after cloning repo)

install:
  # Get the latest and stable version of node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Install modules
  - npm install

# Post-install test script

test_script:
  # Output useful information for debugging
  - node --version
  - npm --version
  # run test
  - npm test

# Dont actually build
build: off